name: Check Idris Sources
on: [push]
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Install Chez Scheme
        run: sudo apt install chezscheme -y
      - name: Install Pack
        run: echo "scheme" > bash -c "$(curl -fsSL https://raw.githubusercontent.com/stefan-hoeck/idris2-pack/main/install.bash)"
      - name: Check idris-stuff Package
        run: ~/.pack/bin/idris2 --typecheck idris-stuff.ipkg
